version: '3.7'

services:
  treasure-app-db:
    image: mysql:8.0
    container_name: treasure-app-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
